### ISSUE TITLE
InternalError: too much recursion

### ISSUE THREAD

**Issue by miguelmota** [monosux/ethereum-block-by-date#18] opened 2021-08-19 22:45 UTC
Hi, I'm running into an `InternalError: too much recursion` error.

![DeepinScreenshot_select-area_20210819154327](https://user-images.githubusercontent.com/168240/130153706-e6c75e42-ae9a-490c-bd5b-7b36b5dec11d.png)

Code:

```js
const blockDater = new BlockDater(provider)
const currentTimestamp = (Date.now() / 1000) | 0
const date = DateTime.fromSeconds(currentTimestamp)
      .minus({ days: 1 })
      .toJSDate()
const info = await blockDater.getDate(date)
```

Any help is appreciated. Thanks!

**Comment by monosux** [comment] 2021-08-20 16:28
Hi @miguelmota,

What is the "DateTime" object in your example? Is it "luxon" package?
Do you use Web3.js or Ethers.js?

**Comment by miguelmota** [comment] 2021-08-20 16:31
@miguelmota sorry yes it's from luxon

```js
import { DateTime } from 'luxon'
```

and it's ethers provider, with rpc url `https://mainnet.optimism.io`

**Comment by monosux** [comment] 2021-08-20 16:33
Also, what is the "ethereum-block-by-date" version you use?

**Comment by miguelmota** [comment] 2021-08-20 16:47
@monosux latest `1.4.0`

![DeepinScreenshot_select-area_20210820094703](https://user-images.githubusercontent.com/168240/130266808-000184ca-802e-4b0e-88e4-656eec1387c9.png)

**Comment by monosux** [comment] 2021-08-20 16:57
Thank you, I was able to reproduce the error. I am investigating it now. I let you know about the results soon.

**Comment by monosux** [comment] 2021-08-20 17:44
Hi,

I am not familiar with the "optimism" solution, but for some reason, it has unusual block time. A lot of blocks have the same timestamp. For example, 67 blocks from 788016 till 788083 have 1629392348 as a timestamp.

For example:

```
let giveMeBlock = await provider.getBlock(788016);
```

Will return 

```
{
  ...
  number: 788016,
  timestamp: 1629392348,
  ...
}
```

And 

```
let giveMeBlock = await provider.getBlock(788083);
```

Will return 

```
{
  ...
  number: 788083,
  timestamp: 1629392348,
  ...
}
```

The same time in blocks, in some moment drives block time difference to 0, and after division by zero, the package has infinity as an argument and infinity recursion as a result.

I can add checking for division by zero (actually I have to add this 😀), and it will solve the infinity recursion problem. But the plugin will not work correctly anyway, because of the same block time in the "optimism" blockchain.

**Comment by monosux** [comment] 2021-08-20 17:48
Here is more information about Block Numbers and Timestamps in Optimism blockchain:

https://community.optimism.io/docs/developers/l2/block-time.html

**Comment by monosux** [comment] 2021-08-20 19:42
Hi,

I published version 1.4.1 of the plugin with a fix for the division by zero error. Please update your dependencies. 

But, as I said, because of the "optimism" block time feature, my plugin will not work correctly with this blockchain.

I am closing the issue for now, please let me know if you need any help.

**Closed by monosux** 2021-08-20 19:42 UTC

**Comment by monosux** [comment] 2021-08-20 21:28
Hi @miguelmota,

Just published version 1.4.2 with a better solution. It should work better for your case. Please update and let me know if it works for you.

**Comment by miguelmota** [comment] 2021-08-21 00:11
@monosux works great!! thanks for the quick fix! 🎉

**Comment by monosux** [comment] 2021-08-21 01:32
Great! You are welcome!
